spring:
  application:
    name: STlog
  datasource:
    url: jdbc:mysql://localhost:3306/I5E2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 10000  # 10초 동안 DB 연결 재시도

  jpa:
    hibernate:
      ddl-auto: update  # update / create / validate / none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

